namespace SeaTurtle.API.Models.Entities;

/// <summary>
/// Represents a uniquely identified sea turtle in the database.
/// TurtleCode (e.g. "t001") is synchronized with FAISS gallery metadata.
/// </summary>
public class Turtle
{
    public Guid Id { get; set; }

    /// <summary>
    /// Unique turtle identifier synchronized with FAISS (e.g. "t001", "t610").
    /// Generated by ai-service's id_generator.
    /// </summary>
    public string TurtleCode { get; set; } = string.Empty;

    /// <summary>Species name (e.g. "Caretta caretta"). Nullable.</summary>
    public string? Species { get; set; }

    /// <summary>Optional friendly nickname for the turtle.</summary>
    public string? Nickname { get; set; }

    /// <summary>Date when this turtle was first observed.</summary>
    public DateTime FirstSeenAt { get; set; } = DateTime.UtcNow;

    /// <summary>Location description of the first sighting.</summary>
    public string? FirstSeenLocation { get; set; }

    /// <summary>Date of the most recent encounter.</summary>
    public DateTime? LastSeenAt { get; set; }

    /// <summary>Soft delete flag.</summary>
    public bool IsDeleted { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    public ICollection<Encounter> Encounters { get; set; } = new List<Encounter>();
    public ICollection<Photo> Photos { get; set; } = new List<Photo>();
}
