"""
Task definitions for the SeaTurtle Photo-ID Research Crew.

Each task includes a callback that automatically logs completion to
docs/project_log.md and uses dynamically generated timestamped filenames
so that multiple runs never overwrite previous outputs.
"""

from crewai import Agent, Task
from crewai.tasks.task_output import TaskOutput

from agents.research_crew.config import (
    CV_RESEARCHER_OUTPUT_DIR,
    DATA_RESEARCHER_OUTPUT_DIR,
    DL_STRATEGIST_OUTPUT_DIR,
    BIOLOGIST_OUTPUT_DIR,
    ORCHESTRATOR_OUTPUT_DIR,
)
from agents.research_crew.utils.log_writer import append_log, generate_output_filename


def _create_task_callback(agent_name: str, output_dir: str):
    """Creates a closure that logs task completion to project_log.md.

    The callback is triggered automatically by CrewAI when the task finishes.
    It extracts a summary from the task output and appends a structured
    log entry following the project's logging standards.

    Args:
        agent_name: The display name for the log entry author field.
        output_dir: The directory path where the agent saved its output.

    Returns:
        Callable: A callback function accepting a TaskOutput argument.
    """
    def callback(output: TaskOutput) -> None:
        raw_output = output.raw if output.raw else "No output produced"
        
        # Save the full output to the agent's directory
        filename = generate_output_filename(f"{agent_name.replace(' ', '_').lower()}_report")
        file_path = output_dir / filename
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(raw_output)

        # Truncate for the log file
        max_summary_length = 500
        summary = raw_output[:max_summary_length]
        if len(raw_output) > max_summary_length:
            summary += "..."

        append_log(
            author=agent_name,
            content=f"Task completed successfully. Output summary: {summary}",
            files_affected=str(file_path),
        )

    return callback


def create_tasks(agents: dict[str, Agent]) -> list[Task]:
    """Creates individual research tasks for all agents.

    Each agent receives the user's request and processes it from their
    domain's perspective. The Orchestrator runs last to synthesize everything.

    Args:
        agents: Dictionary of agents from create_agents(), keyed by role identifier.

    Returns:
        list[Task]: A list containing sequential tasks for the crew.
    """
    data_task = Task(
        description=(
            "Analyze the dataset implications of the following user request:\n\n"
            "User Request: {user_request}\n\n"
            "Focus purely on dataset constraints, augmentation needs, and image quality."
        ),
        expected_output="A brief report on dataset considerations.",
        agent=agents["data_researcher"],
        callback=_create_task_callback("Data Researcher", DATA_RESEARCHER_OUTPUT_DIR)
    )

    cv_task = Task(
        description=(
            "Analyze the computer vision preprocessing implications of the following user request:\n\n"
            "User Request: {user_request}\n\n"
            "Focus purely on image normalization, alignment, and filtering."
        ),
        expected_output="A brief report on CV preprocessing considerations.",
        agent=agents["cv_researcher"],
        callback=_create_task_callback("CV Researcher", CV_RESEARCHER_OUTPUT_DIR)
    )

    dl_task = Task(
        description=(
            "Analyze the deep learning architecture and training metrics based on the following user request:\n\n"
            "User Request: {user_request}\n\n"
            "Focus purely on model metrics (Loss, Accuracy, mAP) and training strategies (Epochs, Overfitting)."
        ),
        expected_output="A detailed report analyzing the model's metrics and training strategy.",
        agent=agents["dl_strategist"],
        callback=_create_task_callback("DL Strategist", DL_STRATEGIST_OUTPUT_DIR)
    )

    bio_task = Task(
        description=(
            "Analyze the biological feasibility of the following user request:\n\n"
            "User Request: {user_request}\n\n"
            "Focus purely on sea turtle anatomy, post-ocular scale patterns, and the biological impact of Few-Shot data."
        ),
        expected_output="A detailed biological analysis of the scale patterns and dataset limitations.",
        agent=agents["biologist"],
        callback=_create_task_callback("Marine Biologist", BIOLOGIST_OUTPUT_DIR)
    )

    orchestrator_task = Task(
        description=(
            "Review the reports generated by the Data Researcher, CV Researcher, DL Strategist, and Marine Biologist "
            "regarding the user request:\n\n"
            "User Request: {user_request}\n\n"
            "Synthesize their findings into a cohesive, final strategic decision document."
        ),
        expected_output="A comprehensive final report synthesizing all expert findings and addressing the user's core question.",
        agent=agents["orchestrator"],
        callback=_create_task_callback("Research Orchestrator", ORCHESTRATOR_OUTPUT_DIR)
    )

    return [data_task, cv_task, dl_task, bio_task, orchestrator_task]
